#!/bin/bash

PHP=`which php`
COMPOSER=`which composer`
NPM=`which npm`

export SYMFONY_ENV=prod

ERROR=`tput setab 1` # background red
GREEN=`tput setab 2` # background green
BACKGROUND=`tput setab 4` # background blue
INFO=`tput setaf 3` # yellow text
BLACKTEXT=`tput setaf 0`
COLOR=`tput setaf 7` # text white
NC=`tput sgr0` # reset

if [[ `echo "$@" | grep '\-\-reset'` ]] || [[ `echo "$@" | grep '\-r'` ]]; then
    RESET=1
else
    RESET=0
fi

function labelText {
    echo -e "\n${BACKGROUND}${COLOR}-> ${1} ${NC}\n"
}

function errorText {
    echo -e "\n${ERROR}${COLOR}=> ${1} <=${NC}\n"
}

function infoText {
    echo -e "\n${INFO}=> ${1} <=${NC}\n"
}

function successText {
    echo -e "\n${GREEN}${BLACKTEXT}=> ${1} <=${NC}\n"
}

function writeErrorMessage {
    if [[ $? != 0 ]]; then
        errorText "${1}"
    fi
}

if [[ "dev" == "$1" ]]; then
    labelText "Development run"
    $COMPOSER install

    labelText "Copy dev index file"
    cp ./app/web/app_dev.php ./web/index.php

#    labelText "Copy dev .htaccess file"
#    cp ./app/web/.htaccess.dev ./web/.htaccess
else
    labelText "PRODUCTION optimize autoloader"
    $COMPOSER install --no-dev -o -a

    labelText "Copy prod index file"
    cp ./app/web/app_prod.php ./web/index.php

#    labelText "Copy prod .htaccess file"
#    cp ./app/web/.htaccess.prod ./web/.htaccess
fi

echo " " >> ./web/index.php
echo "// DO NOT EDIT THIS FILE. WILL BE REWRITTEN AT EVERY RELEASE !!!\n" >> ./web/index.php

labelText "Run setup:install"
$PHP $PWD/bin/console setup:install

labelText "Run assets:install"
$PHP $PWD/bin/console assets:install

labelText "Remove cache files"
find var/cache/* -maxdepth 0 -type d | xargs rm -rf

labelText "Run npm install"
$NPM install

if [[ "dev" == "$1" ]]; then
    $PHP vendor/bin/codecept run
else
    infoText "Not development, no tests run"
fi

successText "Setup finished"

exit 0
