security:

    encoders:
        AppBundle\Entity\UsersEntity: #plaintext
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        database_users:
            entity: { class: Kisphp\NewsletterBundle\Entity\UserEntity }

    firewalls:
        client_area:
            pattern: ^/
            anonymous: ~
            provider: database_users
            form_login:
                check_path: user_login_check
                login_path: user_login
                default_target_path: user_account
                use_referer: false
            logout:
                path: user_logout
                target: homepage
                invalidate_session: true

    access_control:
        - { path: ^/user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/account, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
