security:

    encoders:
        AppBundle\Entity\UserEntity:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        database_users:
            entity: { class: AppBundle\Entity\UserEntity, property: email }

    firewalls:
        client_area:
            pattern: ^/
            anonymous: ~
            provider: database_users
            form_login:
                check_path: security_login_check
                login_path: security_login
                default_target_path: user_account
                use_referer: false
            logout:
                path: security_logout
                target: homepage
                invalidate_session: true

    access_control:
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account, roles: ROLE_SUPER_ADMIN }
        - { path: ^/, roles: ROLE_SUPER_ADMIN }
