services:
  users.security.service:
    class: AppBundle\Services\UserSecurityService
    arguments: ["@security.encoder_factory"]

  twig.app_extensions:
    class: AppBundle\Twig\AppTwigExtensions
    public: false
    tags:
        - { name: twig.extension }