homepage:
    path: /
    defaults: { _controller: KisphpNewsletterBundle:Default:index }

users_routes:
  resource: "@KisphpNewsletterBundle/Resources/config/routes/users.yml"

newsletters:
    path: /newsletters
    defaults: { _controller: KisphpNewsletterBundle:Newsletters:index }

subscribers:
    path: /subscribers
    defaults: { _controller: KisphpNewsletterBundle:Subscribers:index }