homepage:
    path: /
    defaults: { _controller: KisphpNewsletterBundle:Default:index }

users_routes:
  resource: "@KisphpNewsletterBundle/Resources/config/routes/users.yml"

newsletters_routes:
  resource: "@KisphpNewsletterBundle/Resources/config/routes/newsletters.yml"

subscribers:
    path: /subscribers
    defaults: { _controller: KisphpNewsletterBundle:Subscribers:index }