services:
    twig.newsletter_extensions:
        class: Kisphp\NewsletterBundle\Twig\NewsletterExtensions
        arguments: ["@router", "@translator"]
        tags:
            - { name: twig.extension }

    admin.newsletter.service:
        class: Kisphp\NewsletterBundle\Services\NewsletterService
        arguments: ["@doctrine.orm.entity_manager"]

    admin.subscribers.service:
        class: Kisphp\NewsletterBundle\Services\SubscribersService
        arguments: ["@doctrine.orm.entity_manager"]